# Generated by Django 2.0.3 on 2018-03-29 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('condition', models.IntegerField(choices=[(0, 'Ecstatic'), (20, 'Passionate'), (30, 'Happy'), (40, 'Optimistic'), (50, 'Content'), (60, 'Bored'), (62, 'Tired'), (65, 'Hungry'), (70, 'Pessimistic'), (80, 'Frustrated'), (90, 'Overwhelmed'), (100, 'Disappointed'), (110, 'Worried'), (120, 'Angry'), (130, 'Jealous'), (140, 'Insecure'), (150, 'Guilty'), (160, 'Fear'), (170, 'Grief'), (180, 'Despair')])),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
